In [ ]:
number = 193428.45904
print(number)
print(round(number, 2))

193428.45904
193428.46


In [ ]:
million = 1000000
print(f"{million:,}")


1,000,000


In [ ]:
import humanize


# Example usage:
number = 1500000
print(humanize.intword(number))  # Output: 1.5 million
print(f"{number:,}")
print(humanize.intcomma(number, ndigits=2))

number = 23928948012
print(humanize.intword(number))  # Output: 1.5 billion
print(f"{number:,}")
print(humanize.intcomma(number, ndigits=2))

# File size
print(humanize.naturalsize(1_000_000)) # 1.0 MB
print(humanize.naturalsize(1_000_000_000)) # 1.0 GB
print(humanize.naturalsize(1_000_000_000_000)) # 1.0 TB



1.5 million
1,500,000
1,500,000.00
23.9 billion
23,928,948,012
23,928,948,012.00
1.0 MB
1.0 GB
1.0 TB


In [ ]:
# BMI Calculator
import sys

# Function to calculate BMI
def calculate_bmi(weight, height):
    bmi = 0 # initial variable
    bmi = weight / (height ** 2)
    return bmi

# User input for weight and height
weight = float(input("Enter your weight in kilograms: "))
if (weight < 0):
  sys.exit()
height = float(input("Enter your height in meters: "))


# Calculate BMI
bmi = calculate_bmi(weight, height)

# Display the result
print(f"Your BMI is: {bmi:.2f}")

# Interpretation of BMI. Create a if elif else block statement
if (bmi < 18.5):
  print("You are underweight")
elif (18.5 <= bmi < 24.9): # bmi >= 18.5 and bmi < 24.9
  print("you are normal")
elif (25 <= bmi < 29.9):
  print("Overweight")
else:
  print("Obese")

In [ ]:
# Take input for DNA string and store in a variable DNA_string
DNA_string = 'GCTAGCCTACG' # Replace this line with the right code

# Initialize the RNA output as an empty string
RNA_string = ''

# Use "for" loop to traverse the DNA string. Use "If..elif..else" sub block to check and concactenate the appropriate letter
# to RNA_string.
# Use "else" block in the "If..elif..else" sub block to output an error message and break if a diffrent letter is encountered

for i in DNA_string.upper():
    # the upper() method is used to make our program case insensitive
    print(i)
    print("RNA_String:", RNA_string)
    if i == 'G':
        RNA_string = RNA_string + 'C'
    # Continue the "elif" blocks of the "If..elif..else" block for the other letters
    elif i == 'C':
      RNA_string = RNA_string + 'G'
    elif i == 'T':
      RNA_string = RNA_string + 'A'
    elif i == 'A':
      RNA_string = RNA_string + 'U'



    # Complete the "If..elif..else" block with "else" block for an error message assigned to RNA_string
    # break out of the loop


else:
    # This else is attached to the for loop
    print('Done with Translation')

print('DNA output: ', RNA_string)

In [ ]:
fruit = ["banana", "cherry", "grape"]
fruit.insert(1,"apple")
print(fruit)

Remove item from the dictionary

In [ ]:
dict1 = {"name":"Daniel", "age": 23, "degree":"MS"}
print(dict1)
dict1.pop("name")
print(dict1)

{'name': 'Daniel', 'age': 23, 'degree': 'MS'}
{'age': 23, 'degree': 'MS'}


In [ ]:
dict1.popitem()
print(dict1)

{'age': 23}


In [ ]:
dict1.clear()
print(dict1)

{}


In [ ]:
if (len(dict1) > 0):
  dict1.popitem()

Only store the unique items will be saved.

In [ ]:
tech = {'google','amazon','apple','tesla','microsoft','apple', 'google'}
print(tech)

{'apple', 'tesla', 'google', 'amazon', 'microsoft'}


Remove the duplicate from the list

In [ ]:
list1 = ['google','amazon','apple','tesla','microsoft','apple', 'google']
tech_set = set(list1)
print(tech_set)
list2 = list(tech_set)
print(list2)

In [ ]:

text = 'The quick brown fox jumps over a lazy dog'

#Length of the 'text' variable
print(len(text))

#Splitting the string
new = text.split(' ')
print(new)
print(type(new))

#Length of the 'new' variable
print(len(new))
#Middle element of the 'new' variable

if (len(new) % 2 != 0): # for odd number
  middle_index = len(new) // 2
else: # for even number
  middle_index = int(len(new) / 2)

print(middle_index)
#Insert a string to the 'new' variable
new.insert(middle_index, "new_word")
print(new)
string_out = '-'.join(new)
print(string_out)




41
['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'a', 'lazy', 'dog']
<class 'list'>
9
4
['The', 'quick', 'brown', 'fox', 'new_word', 'jumps', 'over', 'a', 'lazy', 'dog']
The-quick-brown-fox-new_word-jumps-over-a-lazy-dog


In [ ]:
text = 'The quick brown fox jumps over a lazy dog'

#Splitting the string
new = text.split(' ')

if (len(new) % 2 != 0): # for odd number
  middle_index = len(new) // 2
else: # for even number
  middle_index = int(len(new) / 2)

print(middle_index)
new_list = new[0:middle_index]
new_list.append("another_word")
print(new_list)


## it is not expected result
new_list.append(new[middle_index:])
print(new_list)
## it is not expected result




4
['The', 'quick', 'brown', 'fox', 'another_word']
['The', 'quick', 'brown', 'fox', 'another_word', ['jumps', 'over', 'a', 'lazy', 'dog']]


Reindex the row after the deletion

In [ ]:
import pandas as pd
import numpy as np

# From a dictionary
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'city': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
print(df)


      name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [ ]:
# Dropping a row
df = df.drop(index=0).reset_index(drop=True)
print(df)

      name  age         city
0      Bob   30  Los Angeles
1  Charlie   35      Chicago


In [ ]:
# From a list of dictionaries
data2 = [
    {'name': 'Alice', 'age': 25, 'city': 'New York'},
    {'name': 'Bob', 'age': 30, 'city': 'Los Angeles'},
    {'name': 'David', 'age': '35', 'city': 'LA', 'state':'CA'},
    {'name': 'Charlie', 'age': 35, 'city': 'Chicago'}
]
df1 = pd.DataFrame(data2)
print(df1)

      name age         city state
0    Alice  25     New York   NaN
1      Bob  30  Los Angeles   NaN
2    David  35           LA    CA
3  Charlie  35      Chicago   NaN


In [ ]:

df1.dtypes

name     object
age      object
city     object
state    object
dtype: object

In [ ]:
# numpy.isreal(array) : Test element-wise whether it is a real number or not(not infinity or not Not a Number)
# panda.map: The map() function executes a specified function for each item in an iterable. The item is sent to the function as a parameter.
df1['age'].map(np.isreal)


0     True
1     True
2    False
3     True
Name: age, dtype: bool

In [ ]:
arr_3d = np.array([[[1, 2],
                    [4, 3],
                    [7, 4]],
                   [[2, 6],
                    [9, 7],
                    [7, 5]],
                   [[1, 3],
                    [3, 5],
                    [0, 2]],
                   [[9, 7],
                    [6, 4],
                    [9, 8]]])
print(arr_3d)
arr_3d[0:2, 1:3, 1]

[[[1 2]
  [4 3]
  [7 4]]

 [[2 6]
  [9 7]
  [7 5]]

 [[1 3]
  [3 5]
  [0 2]]

 [[9 7]
  [6 4]
  [9 8]]]
[[[1 2]
  [4 3]
  [7 4]]

 [[2 6]
  [9 7]
  [7 5]]

 [[1 3]
  [3 5]
  [0 2]]

 [[9 7]
  [6 4]
  [9 8]]]


array([[3, 4],
       [7, 5]])

In [ ]:
arr_3d[0:2]

array([[[1, 2],
        [4, 3],
        [7, 4]],

       [[2, 6],
        [9, 7],
        [7, 5]]])

In [ ]:
arr_3d[0:2, 1:3]

array([[[4, 3],
        [7, 4]],

       [[9, 7],
        [7, 5]]])

In [ ]:
arr_3d[0:2, 1:3, 1]

array([[3, 4],
       [7, 5]])

In [ ]:
%pip install pandasql

  Preparing metadata (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26772 sha256=f9c9b7267be8294276003fcd03b7451b0142c583781d8e446abb9d1142bcaa82
  Stored in directory: /root/.cache/pip/wheels/e9/bc/3a/8434bdcccf5779e72894a9b24fecbdcaf97940607eaf4bcdf9
Successfully built pandasql


In [ ]:
  import pandas as pd
import pandasql as ps

df = pd.DataFrame([[1234, 'Customer A', '123 Street', np.nan],
               [1234, 'Customer A', np.nan, '333 Street'],
               [1233, 'Customer B', '444 Street', '333 Street'],
              [1233, 'Customer B', '444 Street', '666 Street']], columns=
['ID', 'Customer', 'Billing Address', 'Shipping Address'])

q1 = """SELECT ID FROM df """
ps.sqldf(q1)

ID
0  1234
1  1234
2  1233
3  1233

In [ ]:
def divide():
  try:
    numerator = int(input('Enter a numerator: '))
    denominator = int(input('Enter a denominator: '))
    result = numerator / denominator
    print(numerator,'over', denominator,'equals', result)
  except ValueError:
    print('Error: numerator and denominator must be valid integers.')
  except ZeroDivisionError:
    print('Error: denominator cannot be zero.')
  except KeyboardInterrupt: # Press "Stop" button
    print('Input Interrupted')
  except Exception as e:
    print('An unexpected error occurred:', e)
  finally: # No matter what the outcome is, it will always run. It is good for any necessary cleanup (e.g., closing connections, releasing resources, etc.).
    print("Python programming is fun !")


def main():
  divide()

main()



Enter a numerator: 34
Enter a denominator: aa
Error: numerator and denominator must be valid integers.
Python programming is fun !


In [ ]:
"""
Let's put together what we've covered in Pandas for the following exercises. Please see the Canvas lab page for hints as needed.

Important: for these exercises, do not hard code row numbers. (i.e., The solutions should work on another similar data set.)

All of these answers will be tables (i.e. no plots).
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# Given a DataFrame from this data. **Do not change this cell!
# Run this cell to load the data.
d = {'category':['citrus','flower','flower','succulent','flower','citrus','vegetable','vegetable','succulent'],\
     'num_in_stock':[19,14,23,30,144,10,345,26,27],\
     'edible':[True,False,True,False,False,True,True,True,False],\
     'decorative': [False,True,True,True,True,False,False,True,True],\
     'unneeded':[3.44,-4.56,3.26,7.32,79.234,-453,445,995,0.48]}
plants = pd.DataFrame(d,index=['Lemon','Camelia','Lavender','Jade','Rose','Lime','Tomato','Flowering Kale','Aeonium Sunburst'])
plants

In [ ]:
# Run this to see the data types of the columns of this data frame.
plants.dtypes

In [ ]:
# One column is not needed (and named "unneeded"). Permanently remove
# this column from the plants data without including the code "plants =..."

del plants['unneeded']
print(plants)

In [ ]:
# Display the entire row only for plants that are both edible and decorative.
# Use DataFrame.loc attribute to access a particular cell in the given Dataframe using the index and column labels.

print(plants.loc[(plants['edible'] == True) & (plants['decorative'] == True)])

In [ ]:
# Display the total number of plants in stock for each category.

print(plants.groupby('category')['num_in_stock'].sum())
plants_category = pd.Series(plants.groupby('category')['num_in_stock'].sum(), name='count').reset_index()
print(type(plants_category))
plants_category

In [ ]:
#plt.figure(figsize = (15,8)) # Use the matplotlib.pyplot.figure() Function to Change the Size of a Seaborn Plot
ax = sns.barplot(x='category', y='count', data=plants_category)
ax.set_ylabel("Count")
ax.set_xlabel("Category")
ax.set_title("Bar plot of Category Count")
plt.show()

In [ ]:
# Get the total number of plants in stock for the plant names that start with "L".
# This one is a challenge

index = plants.index
print(index)

def condition(x):
  return x.startswith('L')

conditioned_index = [idx for idx, element in enumerate(plants.index) if condition(element)]
print(conditioned_index)

print(plants.iloc[conditioned_index])

print("Total: ", plants.iloc[conditioned_index]['num_in_stock'].sum())

In [ ]:
# explain: conditioned_index = [idx for idx, element in enumerate(plants.index) if condition(element)]
print(plants.index) # i.e Index
conditioned_index2 = []
for index in plants.index:
  if index.startswith('L') == True:
    print(f'{index} - yes')
    conditioned_index2.append(index)
  else:
    print(f'{index} - no')

print(conditioned_index2)